//
//  MealsDataProviderStub.swift
//  Ten Elephants
//
//  Created by Дарья Домрачева on 10.12.2021.
//

import Foundation

final class MealsDataProviderStub: MealsDataProvider {
    func fetchRandomMeals(completionHandler: @escaping MealsFetchCompletion) {
        do {
            let meals = try JSONDecoder().decode(Meals.self, from: stubDataMeal)
            completionHandler(.success(meals))
        } catch {
            completionHandler(.failure(.unparsableData))
        }
    }

    func fetchRandomPreviewMeals(completionHandler: @escaping MealsFetchCompletion) {
        do {
            let meals = try JSONDecoder().decode(Meals.self, from: stubDataMealPreview)
            completionHandler(.success(meals))
        } catch {
            completionHandler(.failure(.unparsableData))
        }
    }
}

fileprivate let stubDataMeal = """
{
"meals" : [
 {
    "dateModified" : null,
    "idMeal" : "52927",
    "strArea" : "Canadian",
    "strCategory" : "Beef",
    "strCreativeCommonsConfirmed" : null,
    "strDrinkAlternate" : null,
    "strImageSource" : null,
    "strIngredient1" : "Beef Brisket",
    "strIngredient10" : "Paprika",
    "strIngredient11" : "Garlic",
    "strIngredient12" : "Onion",
    "strIngredient13" : "Dill",
    "strIngredient14" : "English Mustard",
    "strIngredient15" : "Celery Salt",
    "strIngredient16" : "Red Pepper Flakes",
    "strIngredient17" : "",
    "strIngredient18" : "",
    "strIngredient19" : "",
    "strIngredient2" : "Salt",
    "strIngredient20" : "",
    "strIngredient3" : "Black Pepper",
    "strIngredient4" : "Coriander",
    "strIngredient5" : "Sugar",
    "strIngredient6" : "Bay Leaf",
    "strIngredient7" : "Cloves",
    "strIngredient8" : "Black Pepper",
    "strIngredient9" : "Coriander",
    "strInstructions" : "To make the cure...",
    "strMeal" : "Montreal Smoked Meat",
    "strMealThumb" : "https://www.themealdb.com/images/media/meals/uttupv1511815050.jpg",
    "strMeasure1" : "1",
    "strMeasure10" : "1 tbs",
    "strMeasure11" : "1 tbs",
    "strMeasure12" : "1 tbs",
    "strMeasure13" : "1 tbs",
    "strMeasure14" : "1 tsp ",
    "strMeasure15" : "1 tbs",
    "strMeasure16" : "1 tsp ",
    "strMeasure17" : "",
    "strMeasure18" : "",
    "strMeasure19" : "",
    "strMeasure2" : "3 tbs",
    "strMeasure20" : "",
    "strMeasure3" : "3 tbs",
    "strMeasure4" : "1 tbs",
    "strMeasure5" : "1 tbs",
    "strMeasure6" : "1 tsp ",
    "strMeasure7" : "1 tsp ",
    "strMeasure8" : "3 tbs",
    "strMeasure9" : "1 tbs",
    "strSource" : "http://www.meatwave.com/blog/montreal-smoked-meat-recipe",
    "strTags" : "Speciality,Snack,StrongFlavor",
    "strYoutube" : "https://www.youtube.com/watch?v=g5oCDoyxbBk"
 }
]
}
""".data(using: .utf8)!

fileprivate let stubDataMealPreview = """
{
 "meals" : [
    {
       "dateModified" : null,
       "idMeal" : "53063",
       "strArea" : "Unknown",
       "strCategory" : "Beef",
       "strCreativeCommonsConfirmed" : null,
       "strDrinkAlternate" : null,
       "strImageSource" : null,
       "strIngredient1" : "Beef Brisket",
       "strIngredient10" : "Pepper",
       "strIngredient11" : "",
       "strIngredient12" : "",
       "strIngredient13" : "",
       "strIngredient14" : "",
       "strIngredient15" : "",
       "strIngredient16" : "",
       "strIngredient17" : "",
       "strIngredient18" : "",
       "strIngredient19" : "",
       "strIngredient2" : "Bread",
       "strIngredient20" : "",
       "strIngredient3" : "Lettuce",
       "strIngredient4" : "Tomato",
       "strIngredient5" : "Ham",
       "strIngredient6" : "Mozzarella",
       "strIngredient7" : "Bacon",
       "strIngredient8" : "Egg",
       "strIngredient9" : "Onion",
       "strInstructions" : "Crush the meat so that it is finite and we put it on a griddle to brown. Put the eggs, bacon and ham to fry.\\r\\nCut the bread in half, put the beef brisket, the fried eggs, the bacon, the ham, the mozzarella, the tomato and the lettuce. Cover with the other half of the bread and serve.",
       "strMeal" : "Chivito uruguayo",
       "strMealThumb" : "https://www.themealdb.com/images/media/meals/n7qnkb1630444129.jpg",
       "strMeasure1" : "2",
       "strMeasure10" : "1",
       "strMeasure11" : " ",
       "strMeasure12" : " ",
       "strMeasure13" : " ",
       "strMeasure14" : " ",
       "strMeasure15" : " ",
       "strMeasure16" : " ",
       "strMeasure17" : " ",
       "strMeasure18" : " ",
       "strMeasure19" : " ",
       "strMeasure2" : "2",
       "strMeasure20" : " ",
       "strMeasure3" : "1",
       "strMeasure4" : "1",
       "strMeasure5" : "100g ",
       "strMeasure6" : "100g ",
       "strMeasure7" : "100g ",
       "strMeasure8" : "1",
       "strMeasure9" : "1",
       "strSource" : "https://cookpad.com/uy/recetas/116102-chivito-uruguayo",
       "strTags" : null,
       "strYoutube" : "https://www.youtube.com/watch?v=0PXbbL1QdaA&ab_channel=D%C3%ADadeCocina"
    },
    {
       "dateModified" : null,
       "idMeal" : "53062",
       "strArea" : "Croatian",
       "strCategory" : "Dessert",
       "strCreativeCommonsConfirmed" : null,
       "strDrinkAlternate" : null,
       "strImageSource" : null,
       "strIngredient1" : "Flour",
       "strIngredient10" : "Brown Sugar",
       "strIngredient11" : "Cinnamon",
       "strIngredient12" : "Milk",
       "strIngredient13" : "Icing Sugar",
       "strIngredient14" : "",
       "strIngredient15" : "",
       "strIngredient16" : "",
       "strIngredient17" : "",
       "strIngredient18" : "",
       "strIngredient19" : "",
       "strIngredient2" : "Caster Sugar",
       "strIngredient20" : "",
       "strIngredient3" : "Yeast",
       "strIngredient4" : "Salt",
       "strIngredient5" : "Milk",
       "strIngredient6" : "Eggs",
       "strIngredient7" : "Butter",
       "strIngredient8" : "Walnuts",
       "strIngredient9" : "Butter",
       "strInstructions" : "Mix all the ingredients for the dough together and knead well. Cover the dough and put to rise until doubled in size which should take about 2 hours. Knock back the dough and knead lightly.\\r\\n\\r\\nDivide the dough into two equal pieces; roll each piece into an oblong about 12 inches by 8 inches. Mix the filling ingredients together and divide between the dough, spreading over each piece. Roll up the oblongs as tightly as possible to give two 12 inch sausages. Place these side by side, touching each other, on a greased baking sheet. Cover and leave to rise for about 40 minutes. Heat oven to 200ºC (425ºF). Bake for 30-35 minutes until well risen and golden brown. Bread should sound hollow when the base is tapped.\\r\\n\\r\\nRemove from oven and brush the hot bread top with milk. Sift with a generous covering of icing sugar.",
       "strMeal" : "Walnut Roll Gužvara",
       "strMealThumb" : "https://www.themealdb.com/images/media/meals/u9l7k81628771647.jpg",
       "strMeasure1" : "450g",
       "strMeasure10" : "85g",
       "strMeasure11" : "1 tsp ",
       "strMeasure12" : "To Glaze",
       "strMeasure13" : "To Glaze",
       "strMeasure14" : " ",
       "strMeasure15" : " ",
       "strMeasure16" : " ",
       "strMeasure17" : " ",
       "strMeasure18" : " ",
       "strMeasure19" : " ",
       "strMeasure2" : "55g",
       "strMeasure20" : " ",
       "strMeasure3" : "2 parts ",
       "strMeasure4" : "1/2 tsp",
       "strMeasure5" : "6 oz ",
       "strMeasure6" : "2 Beaten ",
       "strMeasure7" : "30g",
       "strMeasure8" : "140g",
       "strMeasure9" : "85g",
       "strSource" : "https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/",
       "strTags" : "Nutty",
       "strYoutube" : "https://www.youtube.com/watch?v=Q_akngSJVrQ"
    },
    {
       "dateModified" : null,
       "idMeal" : "53061",
       "strArea" : "Croatian",
       "strCategory" : "Side",
       "strCreativeCommonsConfirmed" : null,
       "strDrinkAlternate" : null,
       "strImageSource" : null,
       "strIngredient1" : "Sardines",
       "strIngredient10" : "",
       "strIngredient11" : "",
       "strIngredient12" : "",
       "strIngredient13" : "",
       "strIngredient14" : "",
       "strIngredient15" : "",
       "strIngredient16" : "",
       "strIngredient17" : "",
       "strIngredient18" : "",
       "strIngredient19" : "",
       "strIngredient2" : "Vegetable Oil",
       "strIngredient20" : "",
       "strIngredient3" : "Flour",
       "strIngredient4" : "Salt",
       "strIngredient5" : "",
       "strIngredient6" : "",
       "strIngredient7" : "",
       "strIngredient8" : "",
       "strIngredient9" : "",
       "strInstructions" : "Wash the fish under the cold tap. Roll in the flour and deep fry in oil until crispy. Lay on kitchen towel to get rid of the excess oil and serve hot or cold with a slice of lemon.",
       "strMeal" : "Fresh sardines",
       "strMealThumb" : "https://www.themealdb.com/images/media/meals/nv5lf31628771380.jpg",
       "strMeasure1" : "500g",
       "strMeasure10" : " ",
       "strMeasure11" : " ",
       "strMeasure12" : " ",
       "strMeasure13" : " ",
       "strMeasure14" : " ",
       "strMeasure15" : " ",
       "strMeasure16" : " ",
       "strMeasure17" : " ",
       "strMeasure18" : " ",
       "strMeasure19" : " ",
       "strMeasure2" : "Dash",
       "strMeasure20" : " ",
       "strMeasure3" : "To Glaze",
       "strMeasure4" : "Dash",
       "strMeasure5" : " ",
       "strMeasure6" : " ",
       "strMeasure7" : " ",
       "strMeasure8" : " ",
       "strMeasure9" : " ",
       "strSource" : "https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/",
       "strTags" : "Fresh",
       "strYoutube" : "https://www.youtube.com/watch?v=DDaZoXP1Mdc"
    },
    {
       "dateModified" : null,
       "idMeal" : "53060",
       "strArea" : "Croatian",
       "strCategory" : "Side",
       "strCreativeCommonsConfirmed" : null,
       "strDrinkAlternate" : null,
       "strImageSource" : null,
       "strIngredient1" : "Filo Pastry",
       "strIngredient10" : "",
       "strIngredient11" : "",
       "strIngredient12" : "",
       "strIngredient13" : "",
       "strIngredient14" : "",
       "strIngredient15" : "",
       "strIngredient16" : "",
       "strIngredient17" : "",
       "strIngredient18" : "",
       "strIngredient19" : "",
       "strIngredient2" : "Minced Beef",
       "strIngredient20" : "",
       "strIngredient3" : "Onion",
       "strIngredient4" : "Oil",
       "strIngredient5" : "Salt",
       "strIngredient6" : "Pepper",
       "strIngredient7" : "",
       "strIngredient8" : "",
       "strIngredient9" : "",
       "strInstructions" : "Fry the finely chopped onions and minced meat in oil. Add the salt and pepper. Grease a round baking tray and put a layer of pastry in it. Cover with a thin layer of filling and cover this with another layer of filo pastry which must be well coated in oil. Put another layer of filling and cover with pastry. When you have five or six layers, cover with filo pastry, bake at 200ºC/392ºF for half an hour and cut in quarters and serve.",
       "strMeal" : "Burek",
       "strMealThumb" : "https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg",
       "strMeasure1" : "1 Packet",
       "strMeasure10" : " ",
       "strMeasure11" : " ",
       "strMeasure12" : " ",
       "strMeasure13" : " ",
       "strMeasure14" : " ",
       "strMeasure15" : " ",
       "strMeasure16" : " ",
       "strMeasure17" : " ",
       "strMeasure18" : " ",
       "strMeasure19" : " ",
       "strMeasure2" : "150g",
       "strMeasure20" : " ",
       "strMeasure3" : "150g",
       "strMeasure4" : "40g",
       "strMeasure5" : "Dash",
       "strMeasure6" : "Dash",
       "strMeasure7" : " ",
       "strMeasure8" : " ",
       "strMeasure9" : " ",
       "strSource" : "https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/",
       "strTags" : "Streetfood, Onthego",
       "strYoutube" : "https://www.youtube.com/watch?v=YsJXZwE5pdY"
    },
    {
       "dateModified" : null,
       "idMeal" : "53059",
       "strArea" : "Croatian",
       "strCategory" : "Side",
       "strCreativeCommonsConfirmed" : null,
       "strDrinkAlternate" : null,
       "strImageSource" : null,
       "strIngredient1" : "Mushrooms",
       "strIngredient10" : "Parsley",
       "strIngredient11" : "",
       "strIngredient12" : "",
       "strIngredient13" : "",
       "strIngredient14" : "",
       "strIngredient15" : "",
       "strIngredient16" : "",
       "strIngredient17" : "",
       "strIngredient18" : "",
       "strIngredient19" : "",
       "strIngredient2" : "Buckwheat",
       "strIngredient20" : "",
       "strIngredient3" : "Vegetable Oil",
       "strIngredient4" : "Onion",
       "strIngredient5" : "Garlic",
       "strIngredient6" : "Bay Leaf",
       "strIngredient7" : "Vegetable Stock Cube",
       "strIngredient8" : "Sour Cream",
       "strIngredient9" : "White Wine Vinegar",
       "strInstructions" : "Chop the onion and garlic, slice the mushrooms and wash the buckwheat. Heat the oil and lightly sauté the onion. Add the mushrooms and the garlic and continue to sauté. Add the salt, vegetable seasoning, buckwheat and the bay leaf and cover with water. Simmer gently and just before it is completely cooked, add pepper, sour cream mixed with flour, the chopped parsley and vinegar to taste.",
       "strMeal" : "Mushroom soup with buckwheat",
       "strMealThumb" : "https://www.themealdb.com/images/media/meals/1ngcbf1628770793.jpg",
       "strMeasure1" : "150g",
       "strMeasure10" : "Top",
       "strMeasure11" : " ",
       "strMeasure12" : " ",
       "strMeasure13" : " ",
       "strMeasure14" : " ",
       "strMeasure15" : " ",
       "strMeasure16" : " ",
       "strMeasure17" : " ",
       "strMeasure18" : " ",
       "strMeasure19" : " ",
       "strMeasure2" : "50g",
       "strMeasure20" : " ",
       "strMeasure3" : "4 tbs",
       "strMeasure4" : "40g",
       "strMeasure5" : "2 cloves",
       "strMeasure6" : "1",
       "strMeasure7" : "1tbsp",
       "strMeasure8" : "50 ml ",
       "strMeasure9" : "Dash",
       "strSource" : "https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/",
       "strTags" : "Warming, Soup",
       "strYoutube" : "https://www.youtube.com/watch?v=M1ok7mG9-Qc"
    },
    {
       "dateModified" : null,
       "idMeal" : "53058",
       "strArea" : "Croatian",
       "strCategory" : "Beef",
       "strCreativeCommonsConfirmed" : null,
       "strDrinkAlternate" : null,
       "strImageSource" : null,
       "strIngredient1" : "Cannellini Beans",
       "strIngredient10" : "",
       "strIngredient11" : "",
       "strIngredient12" : "",
       "strIngredient13" : "",
       "strIngredient14" : "",
       "strIngredient15" : "",
       "strIngredient16" : "",
       "strIngredient17" : "",
       "strIngredient18" : "",
       "strIngredient19" : "",
       "strIngredient2" : "Vegetable Oil",
       "strIngredient20" : "",
       "strIngredient3" : "Tomatoes",
       "strIngredient4" : "Challots",
       "strIngredient5" : "Garlic",
       "strIngredient6" : "Parsley",
       "strIngredient7" : "Chorizo",
       "strIngredient8" : "",
       "strIngredient9" : "",
       "strInstructions" : "Heat the oil in a pan. Add the chopped vegetables and sauté until tender. Take a pot, empty the beans together with the vegetables into it, put the sausages inside and cook for further 20 minutes on a low heat. Or, put it in an oven and bake it at a temperature of 180ºC/350ºF for 30 minutes. This dish is even better reheated the next day.",
       "strMeal" : "Croatian Bean Stew",
       "strMealThumb" : "https://www.themealdb.com/images/media/meals/tnwy8m1628770384.jpg",
       "strMeasure1" : "2 cans",
       "strMeasure10" : " ",
       "strMeasure11" : " ",
       "strMeasure12" : " ",
       "strMeasure13" : " ",
       "strMeasure14" : " ",
       "strMeasure15" : " ",
       "strMeasure16" : " ",
       "strMeasure17" : " ",
       "strMeasure18" : " ",
       "strMeasure19" : " ",
       "strMeasure2" : "3 tbs",
       "strMeasure20" : " ",
       "strMeasure3" : "2 cups ",
       "strMeasure4" : "5",
       "strMeasure5" : "2 cloves",
       "strMeasure6" : "Pinch",
       "strMeasure7" : "1/2 kg chopped ",
       "strMeasure8" : " ",
       "strMeasure9" : " ",
       "strSource" : "https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/",
       "strTags" : "Warming, Soup, Beans",
       "strYoutube" : "https://www.youtube.com/watch?v=mrjnQal3S1A"
    },
    {
       "dateModified" : null,
       "idMeal" : "53057",
       "strArea" : "Croatian",
       "strCategory" : "Beef",
       "strCreativeCommonsConfirmed" : null,
       "strDrinkAlternate" : null,
       "strImageSource" : null,
       "strIngredient1" : "Beef",
       "strIngredient10" : "Pepper",
       "strIngredient11" : "Paprika",
       "strIngredient12" : "Vegetable Oil",
       "strIngredient13" : "",
       "strIngredient14" : "",
       "strIngredient15" : "",
       "strIngredient16" : "",
       "strIngredient17" : "",
       "strIngredient18" : "",
       "strIngredient19" : "",
       "strIngredient2" : "Onions",
       "strIngredient20" : "",
       "strIngredient3" : "Carrots",
       "strIngredient4" : "Garlic",
       "strIngredient5" : "Bay Leaf",
       "strIngredient6" : "Red Wine",
       "strIngredient7" : "Water",
       "strIngredient8" : "Mustard",
       "strIngredient9" : "Salt",
       "strInstructions" : "Clean the meat from the veins if there are some and cut it into smaller pieces, 3 × 3 cm. Marinate the meat in the mustard and spices and let it sit in the refrigerator for one hour\\r\\nHeat one tablespoon of pork fat or vegetable oil in a pot and fry the meat on all sides until it gets browned. Once the meat is cooked, transfer it to a plate and add another tablespoon of fat to the pot\\r\\nCut the onions very fine, peel the carrots and shred it using a grater. Cook the onions and carrots over low heat for 15 minutes. You can salt the vegetables a little to make them soften faster\\r\\nOnce the vegetables have browned and become slightly mushy, add the meat and bay leaves and garlic. Pour over with wine and simmer for 10-15 minutes to allow the alcohol to evaporate. Now is the right time to add 2/3 the amount of liquid\\r\\nCover the pot and cook over low heat for an hour, stirring occasionally. After the first hour, pour over the rest of the water or stock and cook for another 30-45 minutes\\r\\nAllow the stew to cool slightly and serve it with a sprinkle of chopped parsley and few slices of fresh hot pepper if you like to spice it up a bit\\r\\nSlice some fresh bread, season the salad and simply enjoying these wonderful flavors",
       "strMeal" : "Traditional Croatian Goulash",
       "strMealThumb" : "https://www.themealdb.com/images/media/meals/n1hcou1628770088.jpg",
       "strMeasure1" : "500g",
       "strMeasure10" : "1/2 tsp",
       "strMeasure11" : "1/2 tsp",
       "strMeasure12" : "2 tbs",
       "strMeasure13" : " ",
       "strMeasure14" : " ",
       "strMeasure15" : " ",
       "strMeasure16" : " ",
       "strMeasure17" : " ",
       "strMeasure18" : " ",
       "strMeasure19" : " ",
       "strMeasure2" : "2 chopped",
       "strMeasure20" : " ",
       "strMeasure3" : "2 chopped",
       "strMeasure4" : "2 cloves",
       "strMeasure5" : "2",
       "strMeasure6" : "200ml",
       "strMeasure7" : "2 Litres",
       "strMeasure8" : "3 tbs",
       "strMeasure9" : "1tbsp",
       "strSource" : "https://www.chasingthedonkey.com/croatian-recipes-traditional-croatian-goulash/",
       "strTags" : "Soup",
       "strYoutube" : "https://www.youtube.com/watch?v=ipEz5u2T7KM"
    },
    {
       "dateModified" : null,
       "idMeal" : "53056",
       "strArea" : "Croatian",
       "strCategory" : "Beef",
       "strCreativeCommonsConfirmed" : null,
       "strDrinkAlternate" : null,
       "strImageSource" : null,
       "strIngredient1" : "Potatoes",
       "strIngredient10" : "Olive Oil",
       "strIngredient11" : "Thyme",
       "strIngredient12" : "White Wine",
       "strIngredient13" : "Pepper",
       "strIngredient14" : "",
       "strIngredient15" : "",
       "strIngredient16" : "",
       "strIngredient17" : "",
       "strIngredient18" : "",
       "strIngredient19" : "",
       "strIngredient2" : "Courgettes",
       "strIngredient20" : "",
       "strIngredient3" : "Carrots",
       "strIngredient4" : "Green Pepper",
       "strIngredient5" : "Aubergine",
       "strIngredient6" : "Onion",
       "strIngredient7" : "Lamb Shoulder",
       "strIngredient8" : "Garlic Sauce",
       "strIngredient9" : "Tomato Puree",
       "strInstructions" : "Preheat oven to 200°C fan / 220°C / 425°F / Gas mark 7\\r\\nIf you have not bought diced lamb, cut your lamb shoulder or leg into large chunks and place to one side.\\r\\nChunks of chopped lamb of a red chopping board\\r\\nMake oil marinade -\\r\\nMix 80ml of olive oil in a bowl with garlic puree, sundried tomato puree ,black pepper and salt.\\r\\nolive oil, gia sundried tomato puree and gia garlic puree and black pepper mixed together in a silver bowl to make Croatian peka\\r\\nAdd potatoes and vegetables into a large lidded casserole dish.\\r\\nChopped up vegetables which consist of chopped up red onion, courgette, potatoes red peppers in a cast iron pan\\r\\nPlace diced lamb on top of the vegetables, pour the marinade and wine over the top.\\r\\nChunks of lamb covered in in a sundried tomato oil sauce which is on top of chopped red onion, aubergine, courgette and potatoes in a cast iron pan\\r\\nAdd the rosemary, thyme and sage, trying to keep the herbs on top.\\r\\nSo you can easily remove the herb stalks once cooked.\\r\\nChunks of lamb coated in a sundried tomato oil sauce and covered with thyme, rosemary and sage which is on top of chopped red onion, aubergine, courgette and potatoes in a cast iron pan\\r\\nPlace lid on the casserole dish and cook for 1hr 30 minute\\r\\nIf you do not have a lid cover very well with kitchen foil\\r\\nCast iron dish with lid on in the oven\\r\\nTake the lid off, remove any thick herb stems. Stir in 2 tbsp of olive oil.\\r\\nCook for a further 20-30 mins.\\r\\nCooked Croatian Lamb Peka in a cast iron pan in the oven\\r\\nServe with fresh homemade bread to dip into the juices.",
       "strMeal" : "Croatian lamb peka",
       "strMealThumb" : "https://www.themealdb.com/images/media/meals/pn59o51628769837.jpg",
       "strMeasure1" : "600g",
       "strMeasure10" : "80 ml ",
       "strMeasure11" : "Sprinking",
       "strMeasure12" : "250ml",
       "strMeasure13" : "Pinch",
       "strMeasure14" : " ",
       "strMeasure15" : " ",
       "strMeasure16" : " ",
       "strMeasure17" : " ",
       "strMeasure18" : " ",
       "strMeasure19" : " ",
       "strMeasure2" : "1 chopped",
       "strMeasure20" : " ",
       "strMeasure3" : "1 chopped",
       "strMeasure4" : "1 chopped",
       "strMeasure5" : "1 small",
       "strMeasure6" : "1 Large Chopped",
       "strMeasure7" : "800g",
       "strMeasure8" : "1 tbs",
       "strMeasure9" : "1 tbs",
       "strSource" : "https://flawlessfood.co.uk/croatian-lamb-peka/",
       "strTags" : null,
       "strYoutube" : "https://www.youtube.com/watch?v=K0ipnz4fwJI"
    },
    {
       "dateModified" : null,
       "idMeal" : "53055",
       "strArea" : "Croatian",
       "strCategory" : "Beef",
       "strCreativeCommonsConfirmed" : null,
       "strDrinkAlternate" : null,
       "strImageSource" : null,
       "strIngredient1" : "Minced Beef",
       "strIngredient10" : "Vegetable Stock Cube",
       "strIngredient11" : "Salt",
       "strIngredient12" : "Pepper",
       "strIngredient13" : "",
       "strIngredient14" : "",
       "strIngredient15" : "",
       "strIngredient16" : "",
       "strIngredient17" : "",
       "strIngredient18" : "",
       "strIngredient19" : "",
       "strIngredient2" : "Minced Pork",
       "strIngredient20" : "",
       "strIngredient3" : "Onion",
       "strIngredient4" : "Garlic",
       "strIngredient5" : "Parsley",
       "strIngredient6" : "Paprika",
       "strIngredient7" : "Baking Powder",
       "strIngredient8" : "Breadcrumbs",
       "strIngredient9" : "Water",
       "strInstructions" : "Place the ground meat in a bowl. Chop the onion very finely and grate the garlic cloves. Add to the bowl. Add the chopped parsley, all sorts of paprika, baking soda, dried breadcrumbs, water, Vegeta, salt, and pepper.\\r\\nMix well with the hand mixer fitted with the dough hooks. Cover the bowl with cling film/ plastic foil and leave to rest for 1 or 2 hours in the refrigerator.\\r\\nTake portions of the meat mixture, about 50-55 g/ 1.7-1.9 oz/ ¼ cup portions, and form the cevapi. The rolls should be about as thick as your thumb and about 7-10 cm/ 3-4 inches long. I had 18 sausages. The recipe can be easily doubled.\\r\\nGrill the cevapcici on the hot grill pan or on the barbecue for about 12-14 minutes, turning them several times in between, or until brown and cooked through. I checked by cutting one in the middle and then grilling the following batches for the same period of time.\\r\\nServe hot as suggested above. The cevapcici can be reheated in the oven at 180 degrees Celsius/ 350 degrees Fahrenheit for about 10 minutes or until heated through. Check one, if it is not hot enough, give the sausages a few more minutes.",
       "strMeal" : "Cevapi Sausages",
       "strMealThumb" : "https://www.themealdb.com/images/media/meals/vc08jn1628769553.jpg",
       "strMeasure1" : "500g",
       "strMeasure10" : "1",
       "strMeasure11" : "1 tsp ",
       "strMeasure12" : "1 tsp ",
       "strMeasure13" : " ",
       "strMeasure14" : " ",
       "strMeasure15" : " ",
       "strMeasure16" : " ",
       "strMeasure17" : " ",
       "strMeasure18" : " ",
       "strMeasure19" : " ",
       "strMeasure2" : "250g",
       "strMeasure20" : " ",
       "strMeasure3" : "1",
       "strMeasure4" : "4 cloves",
       "strMeasure5" : "3 tblsp chopped",
       "strMeasure6" : "1 tbs",
       "strMeasure7" : "3/4 teaspoon",
       "strMeasure8" : "2 tbs",
       "strMeasure9" : "3 tbs",
       "strSource" : "https://whereismyspoon.co/cevapi-or-cevapcici-recipe-grilled-sausages-croatian-food/",
       "strTags" : "Sausages",
       "strYoutube" : "https://www.youtube.com/watch?v=_MpSxSgS7f8"
    },
    {
       "dateModified" : null,
       "idMeal" : "53054",
       "strArea" : "Malaysian",
       "strCategory" : "Dessert",
       "strCreativeCommonsConfirmed" : null,
       "strDrinkAlternate" : null,
       "strImageSource" : null,
       "strIngredient1" : "Rice",
       "strIngredient10" : "",
       "strIngredient11" : "",
       "strIngredient12" : "",
       "strIngredient13" : "",
       "strIngredient14" : "",
       "strIngredient15" : "",
       "strIngredient16" : "",
       "strIngredient17" : "",
       "strIngredient18" : "",
       "strIngredient19" : "",
       "strIngredient2" : "Coconut Milk",
       "strIngredient20" : "",
       "strIngredient3" : "Water",
       "strIngredient4" : "Salt",
       "strIngredient5" : "Corn Flour",
       "strIngredient6" : "Flour",
       "strIngredient7" : "Eggs",
       "strIngredient8" : "Coconut Cream",
       "strIngredient9" : "Sugar",
       "strInstructions" : "Soak glutinous rice with water for at least 1 ½ hours prior to using. Drain.\\r\\nPrepare a 9-inch round or square cake pan and spray with cooking spray or line with plastic wrap.\\r\\nMix coconut milk, water, salt and the rice. Pour it into cake pan, topped with the pandan knots.\\r\\nSteam for 30 minutes.\\r\\nAfter 30 minutes, fluff up the rice and remove pandan knots. Then, using a greased spatula, flatten the steamed rice. Make sure there are no holes/air bubbles and gaps in the rice, especially the sides.\\r\\nSteam for another 10 minutes.\\r\\n\\r\\nCombine pandan juice, coconut milk, all purpose flour, cornflour, and sugar. Mix well.\\r\\nAdd eggs and whisk well then strain into a medium sized metal bowl or pot.\\r\\nPlace pandan mixture over simmering water (double boiler or bain-marie)\\r\\nStir continuously and cook till custard starts to thicken. (15 minutes)\\r\\nPour pandan custard into glutinous rice layer, give it a little tap (for air bubbles) and continue to steam for 30 minutes.\\r\\nRemove kuih seri muka from the steamer and allow to cool completely before cutting into rectangles or diamond shapes.",
       "strMeal" : "Seri muka kuih",
       "strMealThumb" : "https://www.themealdb.com/images/media/meals/6ut2og1619790195.jpg",
       "strMeasure1" : "400g",
       "strMeasure10" : " ",
       "strMeasure11" : " ",
       "strMeasure12" : " ",
       "strMeasure13" : " ",
       "strMeasure14" : " ",
       "strMeasure15" : " ",
       "strMeasure16" : " ",
       "strMeasure17" : " ",
       "strMeasure18" : " ",
       "strMeasure19" : " ",
       "strMeasure2" : "150ml",
       "strMeasure20" : " ",
       "strMeasure3" : "100ml",
       "strMeasure4" : "1 tsp ",
       "strMeasure5" : "5 tbs",
       "strMeasure6" : "3 tbs",
       "strMeasure7" : "3",
       "strMeasure8" : "200ml",
       "strMeasure9" : "140g",
       "strSource" : "https://makan.ch/recipe/kuih-seri-muka/",
       "strTags" : null,
       "strYoutube" : "https://www.youtube.com/watch?v=_NJtCfqgaBo"
    }
 ]
}

""".data(using: .utf8)!
